steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pal-flask-app/pal-flask-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pal-flask-app/pal-flask-app:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'flask-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pal-flask-app/pal-flask-app:latest'